build(deps): bump meta from 1.8.0 to 1.9.0 (#151)
[//]: # (dependabot-start)
⚠️  **Dependabot is rebasing this PR** ⚠️ 

Rebasing might not happen immediately, so don't worry if this takes some time.

Note: if you make any changes to this PR yourself, they will take precedence over the rebase.

---

[//]: # (dependabot-end)

Bumps [meta](https://github.com/dart-lang/sdk/tree/main/pkg) from 1.8.0 to 1.9.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md">meta's changelog</a>.</em></p>
<blockquote>
<h2>3.0.0</h2>
<h3>Libraries</h3>
<h4><code>dart:core</code></h4>
<ul>
<li><strong>Breaking change</strong> <a href="https://github.com/dart-lang/sdk/tree/main/pkg/issues/49529">#49529</a>[]:
<ul>
<li>Removed the deprecated <code>List</code> constructor, as it wasn't null safe.
Use list literals (e.g. <code>[]</code> for an empty list or <code>&lt;int&gt;[]</code> for an empty
typed list) or [<code>List.filled</code>][].</li>
<li>Removed the deprecated <code>onError</code> argument on [<code>int.parse</code>][], [<code>double.parse</code>][],
and [<code>num.parse</code>][]. Use the [<code>tryParse</code>][] method instead.</li>
<li>Removed the deprecated [<code>proxy</code>][] and [<code>Provisional</code>][] annotations.
The original <code>proxy</code> annotation has no effect in Dart 2,
and the <code>Provisional</code> type and [<code>provisional</code>][] constant
were only used internally during the Dart 2.0 development process.</li>
<li>Removed the deprecated [<code>Deprecated.expires</code>][] getter.
Use [<code>Deprecated.message</code>][] instead.</li>
<li>Removed the deprecated [<code>CastError</code>][] error.
Use [<code>TypeError</code>][] instead.</li>
<li>Removed the deprecated [<code>FallThroughError</code>][] error. The kind of
fall-through previously throwing this error was made a compile-time
error in Dart 2.0.</li>
<li>Removed the deprecated [<code>NullThrownError</code>][] error. This error is never
thrown from null safe code.</li>
<li>Removed the deprecated [<code>AbstractClassInstantiationError</code>][] error. It was made
a compile-time error to call the constructor of an abstract class in Dart 2.0.</li>
<li>Removed the deprecated [<code>CyclicInitializationError</code>]. Cyclic dependencies are
no longer detected at runtime in null safe code. Such code will fail in other
ways instead, possibly with a StackOverflowError.</li>
<li>Removed the deprecated [<code>NoSuchMethodError</code>][] default constructor.
Use the [<code>NoSuchMethodError.withInvocation</code>][] named constructor instead.</li>
<li>Removed the deprecated [<code>BidirectionalIterator</code>][] class.
Existing bidirectional iterators can still work, they just don't have
a shared supertype locking them to a specific name for moving backwards.</li>
</ul>
</li>
</ul>
<p><a href="https://github.com/dart-lang/sdk/tree/main/pkg/issues/49529">#49529</a>: <a href="https://github-redirect.dependabot.com/dart-lang/sdk/issues/49529">dart-lang/sdk#49529</a>
[<code>List.filled</code>]: <a href="https://api.dart.dev/stable/2.18.6/dart-core/List/List.filled.html">https://api.dart.dev/stable/2.18.6/dart-core/List/List.filled.html</a>
[<code>int.parse</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/int/parse.html">https://api.dart.dev/stable/2.18.4/dart-core/int/parse.html</a>
[<code>double.parse</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/double/parse.html">https://api.dart.dev/stable/2.18.4/dart-core/double/parse.html</a>
[<code>num.parse</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/num/parse.html">https://api.dart.dev/stable/2.18.4/dart-core/num/parse.html</a>
[<code>tryParse</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/num/tryParse.html">https://api.dart.dev/stable/2.18.4/dart-core/num/tryParse.html</a>
[<code>Deprecated.expires</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/Deprecated/expires.html">https://api.dart.dev/stable/2.18.4/dart-core/Deprecated/expires.html</a>
[<code>Deprecated.message</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/Deprecated/message.html">https://api.dart.dev/stable/2.18.4/dart-core/Deprecated/message.html</a>
[<code>AbstractClassInstantiationError</code>]: <a href="https://api.dart.dev/stable/2.17.4/dart-core/AbstractClassInstantiationError-class.html">https://api.dart.dev/stable/2.17.4/dart-core/AbstractClassInstantiationError-class.html</a>
[<code>CastError</code>]: <a href="https://api.dart.dev/stable/2.17.4/dart-core/CastError-class.html">https://api.dart.dev/stable/2.17.4/dart-core/CastError-class.html</a>
[<code>FallThroughError</code>]: <a href="https://api.dart.dev/stable/2.17.4/dart-core/FallThroughError-class.html">https://api.dart.dev/stable/2.17.4/dart-core/FallThroughError-class.html</a>
[<code>NoSuchMethodError</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/NoSuchMethodError/NoSuchMethodError.html">https://api.dart.dev/stable/2.18.4/dart-core/NoSuchMethodError/NoSuchMethodError.html</a>
[<code>NoSuchMethodError.withInvocation</code>]: <a href="https://api.dart.dev/stable/2.18.4/dart-core/NoSuchMethodError/NoSuchMethodError.withInvocation.html">https://api.dart.dev/stable/2.18.4/dart-core/NoSuchMethodError/NoSuchMethodError.withInvocation.html</a>
[<code>CyclicInitializationError</code>]: <a href="https://api.dart.dev/dev/2.19.0-430.0.dev/dart-core/CyclicInitializationError-class.html">https://api.dart.dev/dev/2.19.0-430.0.dev/dart-core/CyclicInitializationError-class.html</a></p>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/dart-lang/sdk/commit/ff37e66a3c880d8ef32d6c3eac7a115e5f12abe4"><code>ff37e66</code></a> Version 1.9.0-dev.10.12</li>
<li><a href="https://github.com/dart-lang/sdk/commit/98af19501d82b366631a4f3856d6b543faa92c5c"><code>98af195</code></a> Version 1.9.0-dev.10.11</li>
<li><a href="https://github.com/dart-lang/sdk/commit/d0900dac67224fc167c8ac9fe73748b650ed6b6a"><code>d0900da</code></a> Version 1.9.0-dev.10.10</li>
<li><a href="https://github.com/dart-lang/sdk/commit/2301150bf1b22884b4a505556e6b36a0b3171138"><code>2301150</code></a> Version 1.9.0-dev.10.8</li>
<li><a href="https://github.com/dart-lang/sdk/commit/c14290dcd6f9939b83e95d301aa0e990d3008bde"><code>c14290d</code></a> Version 1.9.0-dev.10.7</li>
<li><a href="https://github.com/dart-lang/sdk/commit/b76f443d9c80c1037e7a6d5209c47a1e35076cc0"><code>b76f443</code></a> Version 1.9.0-dev.10.6</li>
<li><a href="https://github.com/dart-lang/sdk/commit/8187a67523d61047502fc99e7cdbb09aa5804fd0"><code>8187a67</code></a> Version 1.9.0-dev.10.5</li>
<li><a href="https://github.com/dart-lang/sdk/commit/f042ea93c12a08f21b926267397e2747ac00e7e0"><code>f042ea9</code></a> Version 1.9.0-dev.10.4</li>
<li><a href="https://github.com/dart-lang/sdk/commit/e5b6c015598b97ebb40f776f8599b25a01352308"><code>e5b6c01</code></a> Version 1.9.0-dev.10.3</li>
<li><a href="https://github.com/dart-lang/sdk/commit/347d319d6e97db1f70be11561e4c0e32faf7515f"><code>347d319</code></a> Version 1.9.0-dev.10.1</li>
<li>Additional commits viewable in <a href="https://github.com/dart-lang/sdk/commits/1.9.0/pkg">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=meta&package-manager=pub&previous-version=1.8.0&new-version=1.9.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>